name: app_warner
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - imagens/bart.jpg
  fonts:
    - family: BalooTammudu2
      fonts:
        - asset: fontes/BalooTammudu2-Bold.ttf  
        - asset: fontes/BalooTammudu2-Medium.ttf
    - family: StintUltraCondensed
      fonts:
        - asset: fontes/StintUltraCondensed-Regular.ttf  
 